### ISSUE TITLE
How are you handling returns?

### ISSUE THREAD

**Issue by tesserakt** [bonobos/spree_avatax#59]
Hi guys, 

I see in the README that you don't handle returns. 2.4 is already out and I am wondering how you all were thinking of tackling returns?

**Comment by athal7** [comment]
The README is out of date. the 2-2-dev branch does have return handling.

We set the following to hook the up this extension:
```ruby
Spree::Reimbursement.reimbursement_tax_calculator = lambda do |reimbursement|
  SpreeAvatax::ReturnInvoice.generate(reimbursement)
end
# Avatax invoices need to be finalized
Spree::Reimbursement.reimbursement_success_hooks << lambda do |reimbursement|
  SpreeAvatax::ReturnInvoice.finalize(reimbursement)
end
```

**Comment by tesserakt** [comment]
@athal7 Great. I assume this is based on the 2.4 return stuff? I know this branch is 2-2 but I assume your fork of Spree has the 2-4 return stuff in it?

**Comment by athal7** [comment]
yes exactly

**Comment by tesserakt** [comment]
Thank you sir.
