### ISSUE TITLE
Compatibility with Spree 2.4.x and Spree 3.0.x

### ISSUE THREAD

**Issue by davidoh** [bonobos/spree_avatax#62]
Hi all,

Just wondering what plans are in place to introduce compatibility for Spree 2.4.x and 3.0.x? We don't want to unnecessarily double up on work that is already in progress., however if nothing is underway yet then we can issue a pull request after we finish the upgrade.

Thanks!

**Comment by athal7** [comment]
@davidoh thanks for asking. We are not currently planning to do that work, so pull requests would be fantastic. You will notice an implementation compatible with 2.4's new returns system on the 2-2-dev branch of this repository.

**Comment by davidoh** [comment]
Thank you sir.
